# Generated by Django 4.2.1 on 2023-06-03 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cellphone',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='zipcode',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='complement',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('apelido', models.CharField(blank=True, max_length=30, null=True)),
                ('especie', models.CharField(blank=True, max_length=10, null=True)),
                ('idade', models.CharField(blank=True, max_length=30, null=True)),
                ('porte', models.CharField(blank=True, max_length=30, null=True)),
                ('castrado', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('disponivel', models.BooleanField(default=True)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['id'],
            },
        ),
    ]
