# Generated by Django 4.2.1 on 2023-09-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cellphone_user_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Femea', 'Femea')], max_length=10, null=True),
        ),
    ]
