# Generated by Django 4.2.1 on 2023-10-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_animal_imagem_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
