# Generated by Django 4.2.1 on 2023-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_animal_imagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='animal',
            name='imagem_detalhe',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
